# Generated by Django 2.2.9 on 2019-12-30 05:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_hstore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateTimeField()),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', django_hstore.fields.SerializedDictionaryField()),
                ('request_meta', django_hstore.fields.SerializedDictionaryField()),
                ('status', models.CharField(choices=[(1, 'Unprocessed'), (2, 'Processed'), (3, 'Error')], default=1, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_processed', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_id', models.CharField(max_length=250)),
                ('team_domain', models.CharField(max_length=250)),
                ('channel_id', models.CharField(max_length=250)),
                ('channel_name', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('user_name', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('trigger_word', models.CharField(max_length=250)),
                ('webhook_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webhook.WebhookTransaction')),
            ],
        ),
    ]
