# Generated by Django 3.0.1 on 2019-12-30 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=50, null=True, unique=True)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('employee_id', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('job_position', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordtime', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('humid', models.IntegerField(blank=True, null=True)),
                ('accelX', models.IntegerField(blank=True, null=True)),
                ('accelY', models.IntegerField(blank=True, null=True)),
                ('accelZ', models.IntegerField(blank=True, null=True)),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('gyroX', models.IntegerField(blank=True, null=True)),
                ('gyroY', models.IntegerField(blank=True, null=True)),
                ('gyroZ', models.IntegerField(blank=True, null=True)),
                ('gps_lat', models.CharField(blank=True, max_length=100, null=True)),
                ('gps_lng', models.CharField(blank=True, max_length=100, null=True)),
                ('gps_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('voc', models.IntegerField(blank=True, null=True)),
                ('air_quality', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Hat')),
            ],
        ),
    ]
