# Generated by Django 3.0.1 on 2019-12-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('gps', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('voc', models.IntegerField(blank=True, null=True)),
                ('tof', models.IntegerField(blank=True, null=True)),
                ('humid', models.IntegerField(blank=True, null=True)),
                ('gyro', models.CharField(blank=True, max_length=100, null=True)),
                ('last_connect_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
