# Generated by Django 3.0.1 on 2019-12-25 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hat',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='hat',
            name='gyro',
        ),
        migrations.RemoveField(
            model_name='hat',
            name='humid',
        ),
        migrations.RemoveField(
            model_name='hat',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='hat',
            name='tof',
        ),
        migrations.RemoveField(
            model_name='hat',
            name='voc',
        ),
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordtime', models.DateTimeField(auto_now_add=True)),
                ('gps', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('voc', models.IntegerField(blank=True, null=True)),
                ('humid', models.IntegerField(blank=True, null=True)),
                ('gyro', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Hat')),
            ],
        ),
    ]
