# Generated by Django 3.0.1 on 2019-12-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191231_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sior/static')),
                ('filtered_image', models.ImageField(upload_to='%Y/%m/%d/filtered')),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='hat',
            name='risk_level',
            field=models.CharField(choices=[('정상', 1), ('주의', 2), ('위험', 3)], default=1, max_length=10),
        ),
    ]
