# Generated by Django 3.0.1 on 2019-12-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191225_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
