# Generated by Django 3.0.1 on 2020-01-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191231_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_normal', models.FloatField(blank=True, null=True)),
                ('temperature_warning', models.FloatField(blank=True, null=True)),
                ('temperature_dangerous', models.FloatField(blank=True, null=True)),
                ('humid_normal', models.FloatField(blank=True, null=True)),
                ('humid_warning', models.FloatField(blank=True, null=True)),
                ('humid_dangerous', models.FloatField(blank=True, null=True)),
                ('pressure_normal', models.FloatField(blank=True, null=True)),
                ('pressure_warning', models.FloatField(blank=True, null=True)),
                ('pressure_dangerous', models.FloatField(blank=True, null=True)),
                ('voc_normal', models.FloatField(blank=True, null=True)),
                ('voc_warning', models.FloatField(blank=True, null=True)),
                ('voc_dangerous', models.FloatField(blank=True, null=True)),
                ('air_quality_normal', models.FloatField(blank=True, null=True)),
                ('air_quality_warning', models.FloatField(blank=True, null=True)),
                ('air_quality_dangerous', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
