# Generated by Django 3.0.1 on 2019-12-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_hat_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='last_position_gps',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hat',
            name='last_position_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
