# Generated by Django 3.0.1 on 2019-12-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191226_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hat',
            old_name='last_position_gps',
            new_name='last_location_gps',
        ),
        migrations.RenameField(
            model_name='hat',
            old_name='last_position_str',
            new_name='last_location_str',
        ),
        migrations.AddField(
            model_name='hat',
            name='job_position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
