# Generated by Django 3.0.1 on 2020-01-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200102_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorvalue',
            name='co2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
