# Generated by Django 3.0.1 on 2019-12-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20191226_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hat',
            name='last_location_gps',
        ),
        migrations.AddField(
            model_name='hat',
            name='last_location_gps_lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hat',
            name='last_location_gps_lng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
