# Generated by Django 3.0.1 on 2019-12-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191226_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='employee_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
