# Generated by Django 3.0.1 on 2019-12-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0002_auto_20191225_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorval',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Hat',
        ),
        migrations.DeleteModel(
            name='SensorVal',
        ),
    ]
